-- Operational note (hand-added; drizzle-kit's generated SQL below is
-- otherwise unmodified apart from adding IF NOT EXISTS to both CREATE
-- statements): this project's migration runner (drizzle-kit's built-in
-- `migrate()`, invoked via `npm run db:migrate`) wraps every pending
-- migration file, and every statement in each one, inside a single
-- Postgres transaction. Postgres does not allow CREATE INDEX CONCURRENTLY
-- or DROP INDEX CONCURRENTLY inside a transaction block, so genuinely
-- online/non-blocking index creation is not something this migration
-- tooling can express here - writing CONCURRENTLY into this file would
-- simply make the migration fail outright, not run it safely. This file's
-- plain CREATE/DROP INDEX statements are therefore not lock-free: while
-- each index is being built, Postgres holds a SHARE lock on
-- historical_observations, which blocks concurrent INSERT/UPDATE/DELETE
-- (never SELECT) against it for that statement's duration.
--
-- DROP INDEX is a fast, metadata-only operation regardless of table size -
-- not a practical concern at any point.
--
-- The two CREATE UNIQUE INDEX statements scan and sort the table and are
-- the real cost, proportional to historical_observations' row count at
-- migration time. For a small/dev table (true today) running this
-- migration as-is is fine.
--
-- For a production database where historical_observations has grown large
-- enough that a multi-second write-blocking window would matter, this
-- migration ships an actual companion deploy step, not just a comment to
-- copy SQL from:
--
--   npm run db:migrate:0025-concurrent-indexes
--
-- (lib/database/migrations/scripts/0025-create-block-identity-indexes-concurrently.ts)
-- runs the equivalent CONCURRENTLY statements as plain top-level
-- (non-transactional) calls - the only way Postgres allows CONCURRENTLY at
-- all - before `npm run db:migrate` runs. With IF NOT EXISTS/IF EXISTS on
-- every statement on both sides, running the concurrent script first is
-- always safe, including against a small/dev database or one that already
-- applied this migration the normal way: whichever path ran first leaves
-- nothing for the other to do, so it completes as a fast no-op. This is
-- the safest strategy actually available within this project's migration
-- setup, genuinely integrated into how the project deploys - not a claim
-- of true zero-downtime, since running the concurrent-index script is
-- still a real, separate step an operator (or deploy pipeline) has to
-- take before `db:migrate`, not something `db:migrate` does on its own.
DROP INDEX IF EXISTS "historical_observations_dedup_unique";--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "historical_observations_block_hash_identity_unique" ON "historical_observations" USING btree ("entity_type","entity_id","metric","block_number","block_hash") WHERE "historical_observations"."block_number" is not null and "historical_observations"."block_hash" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "historical_observations_block_only_identity_unique" ON "historical_observations" USING btree ("entity_type","entity_id","metric","block_number") WHERE "historical_observations"."block_number" is not null and "historical_observations"."block_hash" is null;
